### PR TITLE
fix if & ifelse

### PR DESCRIPTION
**Pull request by mathroc**

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
No, using `getValue()` won't work for internal functions. I just needed to rewrite it in terms of `.invoke()`, so `(condition.getValue() ? trueCase : falseCase).invoke();`

**Comment by TazeTSchnitzel** [comment]
Also, tr

**Comment by hikari-no-yume** [comment]
There's also no real need for `getValue` in functions just yet, so I won't add it.

**Comment by mathroc** [comment]
well, `source` returned by `getValue()` for function is actually useful for the `\ast` command in the REPL (see #24). or maybe it should be some other name ?

**Comment by hikari-no-yume** [comment]
Obsoleted by https://github.com/TazeTSchnitzel/Firth/commit/039b22f10b0d639890d1acf6316e0045c21c2f3a

**Comment by mathroc** [comment]
oh, I finally understood what's wrong. when calling `execute`, the first argument needs to be an AST, but in `if` and `ifelse` it "just" a function so `ast,length` is `undefined` and nothing happens.

so it should be either `[trueCase, {type: 'invoke'}]` or `trueCase,getValues()`

**Comment by mathroc** [comment]
or just `trueCase.invoke(stack, scope);` as you just pushed ^^

**Comment by hikari-no-yume** [comment]
I think I'll make `execute` use `forEach` to iterate over the array. `for (var i = 0; i < ast.length; i++)` is an anachronism, and this'll make failure more obvious.

**Comment by hikari-no-yume** [comment]
Done: https://github.com/TazeTSchnitzel/Firth/commit/dbef1d4cc9b61e8d6e386bf5667cc465ca3ecfbe

**Comment by mathroc** [comment]
:+1:

**Pull request closed without merging**
