### PR TITLE
REPL improvements

### PR DESCRIPTION
**Pull request by mathroc**
the P of REPL had been forgotten (#22)

also adds `\clear`, `\reset` and `\help` REPL commands

### CODE REVIEW

**Comment by mathroc** [comment]
I'm also planning to add `\tokens` and `\ast` toggles that would show tokens and ast for debugging purpose

**Comment by hikari-no-yume** [comment]
A thought: it is probably more worthwhile advancing Firth to the point where we can write a REPL in it, than it is continuing to work on a REPL in JavaScript.

**Comment by mathroc** [comment]
hmm I hadn't thought of that yet. 

you mean calling something like `node bin/firth.js repl.txt` to get inside an repl ? (note: what extension should we use instead of `.txt` ? )

I mean we still need at least #1, #5, bindings to the lexer, parser & executor (which probably need List and/or Records) and maybe some exception/error handler

**Comment by hikari-no-yume** [comment]
Yeah. The extension would be `.firth`, naturally. So `./bin/firth.js repl.firth` maybe.

There would be quite a few things necessary for this. Primarily: strings, I/O, dictionaries, possibly lists, some form of `eval` (or `parse`/`execute`).

**Comment by mathroc** [comment]
stalled project (PR cleaning)

**Pull request closed without merging**
