### PR TITLE
npm-packigification

### PR DESCRIPTION
**Pull request by mathroc**
First try at making a npm package out of Firth

interpreting a source file from the CLI works!

gulp build concatenated files but minification & sourcemaps don't work

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
I have to say I'm a bit uneasy with the number of dependencies this adds, and it doesn't really get rid of the IIFEs which is unfortunate

**Comment by hikari-no-yume** [comment]
Also, the compiled output probably shouldn't be in the repository. The whole of `dist` should probably be `.gitignore`d. GitHub's releases system can be used for pre-compiled versions.

**Comment by hikari-no-yume** [comment]
But, otherwise, good work so far!

**Comment by hikari-no-yume** [comment]
Oh, one more thing: four spaces, not tabs, please!

**Comment by mathroc** [comment]
ow, the dependancies are mostly devDeps. I fixed that and the tabs

about the `dist/` folder and what should be inside. in the long run, do you think that `test.html` & `gulpfile.js` shoud be inside the package? to me it should be another repo or maybe in `exemples/web-firth/`

**Comment by mathroc** [comment]
oh, and I can get rid of the IIFEs, I just wanted to do as few changes as possible to existing files

**Comment by hikari-no-yume** [comment]
`test.html` might eventually be moved somewhere, I don't know

**Comment by mathroc** [comment]
well it makes the diff a lot bigger without the IIFEs as github don't, afaik, have a `--ignore-space-changes` option

**Comment by hikari-no-yume** [comment]
Hey, how do I actually use the gulp thing?

**Comment by mathroc** [comment]
I suppose you have `npm` installed on your system already

run `npm install` and then `gulp` it should build 2 files in `dist/` once that's done you can open `test.html` again and it should work as before. 
(`gulp --watch` if you want it to build the file each time a source file is edited) 

but you don't need `gulp` for the CLI tool. for the CLI, after `npm install` just do `./bin/firth.js some-file.txt`

**Comment by mathroc** [comment]
I just added `exemples\web` to try what it would look like to move `test.html` into another folder. it contains the minimum needed Firth into a web project with browserify

 if that's something that could work, I can remove `/gulpfile.js`, `/src/web.js`, `/test.html` and `devDependancies` from `package.json`

let me know what you think

**Comment by hikari-no-yume** [comment]
I see

Well, for starters, the English word is ex_a_mples

**Comment by mathroc** [comment]
since you've already merged the firsts commits, this new version of the PR shows what it would look like with `test.html` only in `examples/web`

**Comment by hikari-no-yume** [comment]
Could be done, but I don't see the point.

**Pull request closed without merging**
